server:
  port: 8080

spring:
  application:
    name: projectplanner
  datasource:
    url: jdbc:postgresql://localhost:5432/project_planner
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    web-application-type: servlet
